
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Leads extends javax.swing.JFrame {

    private int id;
    private Connection conn;
    String leadList;

    Leads(int id,Connection conn) throws SQLException{
        this.id = id;
        System.out.println("GiveLead : "+id);
        this.conn = conn;
        initComponents();
        
        
        try (Statement st = conn.createStatement()) {
            String query = String.format("Select * from LEADS where citizen_id = '%d';",id);
            ResultSet rs = st.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel)lTable.getModel();
            model.setRowCount(0);
            leadList = "";
            while(rs.next()){
                String leadid = rs.getString("lead_id");
                String citizen = rs.getString("citizen_id");
                String ipc = rs.getString("ipc");
                String desc = rs.getString("description");
                String date = rs.getString("report_date");
                String location = rs.getString("location");
                String valid = rs.getString("authority_validation");
                model.addRow(new Object[]{leadid, citizen, ipc, desc, date, location, valid});
                leadList = leadList + ", " +  leadid;
            }
            rs.close();
        }
    }
    /**
     * Creates new form Leads
     */
    public Leads() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lTable = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        delentry = new javax.swing.JButton();
        phoneLabel = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        ipc_crime = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        validation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lead ID", "Citizen ID", "IPC", "Description", "Date", "Location", "Validation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lTable);

        delete.setText("DELETE ALL");
        delete.setToolTipText("");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        delentry.setText("Delete Selected Entry");
        delentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delentryActionPerformed(evt);
            }
        });

        phoneLabel.setText("Location");

        filterButton.setText("Search");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        filterLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        filterLabel.setText("Search by");
        filterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lnameLabel.setText("IPC of crime");

        ipc_crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipc_crimeActionPerformed(evt);
            }
        });

        addressLabel.setText("Validation");

        validation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validation, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ipc_crime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delentry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(delentry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameLabel)
                            .addComponent(ipc_crime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel)
                            .addComponent(addressLabel)
                            .addComponent(validation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            int YesOrNo = JOptionPane.showConfirmDialog(null, "Do You Want to Delete All Leads in the Table?", "Delete Leads", JOptionPane.YES_NO_OPTION);
            if(YesOrNo == 0){
                try {
                    Statement delq = conn.createStatement();
                    String query = String.format("DELETE from LEADS WHERE lead_id IN (" + leadList.substring(2) + ");");
                    System.out.println(query);
                    delq.executeUpdate(query);
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Deleted Successfully");
                } catch (SQLException ex) {
                    Logger.getLogger(Leads.class.getName()).log(Level.SEVERE, null, ex);
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Something went Wrong. Couldn't Delete.");
                }
            }

            try (Statement newtable = conn.createStatement()) {
                String query = String.format("Select * from LEADS where citizen_id = '%d';",id);
                ResultSet rs = newtable.executeQuery(query);
                DefaultTableModel model = (DefaultTableModel)lTable.getModel();
                model.setRowCount(0);
                leadList = "";
                while(rs.next()){
                    String leadid = rs.getString("lead_id");
                    String citizen = rs.getString("citizen_id");
                    String ipc = rs.getString("ipc");
                    String desc = rs.getString("description");
                    String date = rs.getString("report_date");
                    String location = rs.getString("location");
                    String valid = rs.getString("authority_validation");
                    model.addRow(new Object[]{leadid, citizen, ipc, desc, date, location, valid});
                    leadList = leadList + ", " +  leadid;
                }
                rs.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Leads.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void delentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delentryActionPerformed
        int rowIndex =  lTable.getSelectedRow();
        JFrame f = new JFrame();
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(f, "Please Select an Entry To Perform This Operation");
        } else {
            try {
                int YesOrNo = JOptionPane.showConfirmDialog(null, "Do You Want to Delete This Lead?", "Delete Lead", JOptionPane.YES_NO_OPTION);
                if(YesOrNo == 0){
                    try {
                        Statement delq = conn.createStatement();
                        int d = Integer.parseInt(lTable.getValueAt(rowIndex, 0).toString());
                        String query = String.format("DELETE from Leads WHERE lead_id = '" + d + "';");
                        System.out.println(query);
                        delq.executeUpdate(query);
                        JOptionPane.showMessageDialog(f, "Deleted Successfully");
                    } catch (SQLException ex) {
                        Logger.getLogger(Leads.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(f, "Something went Wrong");
                    }
                }

                try (Statement newtable = conn.createStatement()) {
                    String query = String.format("Select * from LEADS where citizen_id = '%d';",id);
                    ResultSet rs = newtable.executeQuery(query);
                    DefaultTableModel model = (DefaultTableModel)lTable.getModel();
                    model.setRowCount(0);
                    leadList = "";
                    while(rs.next()){
                        String leadid = rs.getString("lead_id");
                        String citizen = rs.getString("citizen_id");
                        String ipc = rs.getString("ipc");
                        String desc = rs.getString("description");
                        String date = rs.getString("report_date");
                        String location = rs.getString("location");
                        String valid = rs.getString("authority_validation");
                        model.addRow(new Object[]{leadid, citizen, ipc, desc, date, location, valid});
                        leadList = leadList + ", " +  leadid;
                    }
                    
                    rs.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Leads.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(f, "Something went wrong while Deleting Entry");
            }
        }
    }//GEN-LAST:event_delentryActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:
        try {
            String crime = "%"+ipc_crime.getText()+"%";
            String val = "%"+validation.getText()+"%";
            String loca = "%"+location.getText()+"%";
            Statement st = conn.createStatement();
            String query = String.format("SELECT * from LEADS WHERE ipc LIKE '%s' AND citizen_id = '%d' AND "
                + "authority_validation LIKE '%s' AND location LIKE '%s';", crime, id, val, loca);
            System.out.println(query);
            ResultSet rs = st.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel)lTable.getModel();
            model.setRowCount(0);
            leadList = "";
            while(rs.next()){
                        String leadid = rs.getString("lead_id");
                        String citizen = rs.getString("citizen_id");
                        String ipc = rs.getString("ipc");
                        String desc = rs.getString("description");
                        String date = rs.getString("report_date");
                        String location = rs.getString("location");
                        String valid = rs.getString("authority_validation");
                        model.addRow(new Object[]{leadid, citizen, ipc, desc, date, location, valid});
                        leadList = leadList + ", " +  leadid;
                    }
            rs.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(Leads.class.getName()).log(Level.SEVERE, null, ex);
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Something went Wrong");
        }
    }//GEN-LAST:event_filterButtonActionPerformed

    private void validationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validationActionPerformed

    private void ipc_crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipc_crimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipc_crimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leads().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton delentry;
    private javax.swing.JButton delete;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JTextField ipc_crime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lTable;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField location;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField validation;
    // End of variables declaration//GEN-END:variables
}
