
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Police extends javax.swing.JFrame {
    
    private int id;
    private Connection conn;
    /**
     * Creates new form Police
     */
    public Police() {
        initComponents();
        viewcriminalpanel.setVisible(false);

        
    }
    Police(int id, Connection conn){
        this.id = id;
        System.out.println("Police : "+id);
        this.conn = conn;
        initComponents();
        viewcriminalpanel.setVisible(false);
    }
//    public void close(){
// 
//        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
// 
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewcitizens = new javax.swing.JButton();
        viewcrime = new javax.swing.JButton();
        addcriminals = new javax.swing.JButton();
        viewcriminalrecord = new javax.swing.JButton();
        viewleads = new javax.swing.JButton();
        addcriminalrecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addcrime = new javax.swing.JButton();
        addvictims = new javax.swing.JButton();
        viewcriminalpanel = new javax.swing.JPanel();
        criminaltablepane = new javax.swing.JScrollPane();
        viewcriminaltable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewcitizens.setText("View Citizens");
        viewcitizens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcitizensActionPerformed(evt);
            }
        });

        viewcrime.setText("View Crime");
        viewcrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcrimeActionPerformed(evt);
            }
        });

        addcriminals.setText("Add Criminal(s)");
        addcriminals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcriminalsActionPerformed(evt);
            }
        });

        viewcriminalrecord.setText("Criminal Record");
        viewcriminalrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcriminalrecordActionPerformed(evt);
            }
        });

        viewleads.setText("View Leads");
        viewleads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewleadsActionPerformed(evt);
            }
        });

        addcriminalrecord.setText("Add criminal record");
        addcriminalrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcriminalrecordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME");

        addcrime.setText("Add Crime");
        addcrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcrimeActionPerformed(evt);
            }
        });

        addvictims.setText("View Victims");
        addvictims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvictimsActionPerformed(evt);
            }
        });

        viewcriminaltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name (Alias)", "Crime ", "Judicial Status", "IPC", "Bailable/Non-Bailable", "Punishment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        criminaltablepane.setViewportView(viewcriminaltable);

        javax.swing.GroupLayout viewcriminalpanelLayout = new javax.swing.GroupLayout(viewcriminalpanel);
        viewcriminalpanel.setLayout(viewcriminalpanelLayout);
        viewcriminalpanelLayout.setHorizontalGroup(
            viewcriminalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(viewcriminalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewcriminalpanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criminaltablepane, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        viewcriminalpanelLayout.setVerticalGroup(
            viewcriminalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(viewcriminalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(criminaltablepane, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewcitizens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewleads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addcriminals, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewcriminalrecord))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(viewcrime, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addcriminalrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addvictims, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addcrime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewcriminalpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewcitizens)
                    .addComponent(addcriminals)
                    .addComponent(viewcrime)
                    .addComponent(addcrime))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewcriminalrecord)
                    .addComponent(addcriminalrecord)
                    .addComponent(viewleads)
                    .addComponent(addvictims))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewcriminalpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcriminalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcriminalsActionPerformed
        //close();
        Add_criminal ac = new Add_criminal(id,conn);
        ac.setVisible(true);
    }//GEN-LAST:event_addcriminalsActionPerformed

    private void viewcriminalrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcriminalrecordActionPerformed
        DefaultTableModel criminalT = (DefaultTableModel)viewcriminaltable.getModel();
        criminalT.setRowCount(0);
        PreparedStatement pst,pst1,pst2;
        String criminalid=null;
        try {
            pst = conn.prepareStatement("select criminal_id,first_name,last_name,alias,judicial_status from criminal;"); 
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
            criminalid=rs.getString("criminal_id");
            System.out.println(criminalid);
            pst1 = conn.prepareStatement("select punishment,ipc from criminalrecord where criminal_id=?");
            pst1.setString(1,criminalid);
            ResultSet rs1 = pst1.executeQuery();
            rs1.first();
            String ipc=rs1.getString("ipc");
            pst2 = conn.prepareStatement("select description,bailable from crime where ipc=?");
            pst2.setInt(1,Integer.parseInt(ipc));
            ResultSet rs2 = pst2.executeQuery();
            rs2.first();
            int i = 0; 
             
            String  name = rs.getString("first_name")+" "+rs.getString("last_name")+" ("+rs.getString("alias")+")";
            String  crime = rs2.getString("description");
            String  jstatus = rs.getString("judicial_status");
            String bail = rs2.getString("bailable");
            String punishment = rs1.getString("punishment");
            criminalT.addRow(new Object[]{ name, crime, jstatus, ipc, bail, punishment});
            i++;
            viewcriminalpanel.setVisible(true);
            }
        }catch(Exception ex){
            Logger.getLogger(Police.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewcriminalrecordActionPerformed

    private void addcriminalrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcriminalrecordActionPerformed
        add_criminalrecord acr=new add_criminalrecord(conn);
        acr.setVisible(true);
    }//GEN-LAST:event_addcriminalrecordActionPerformed

    private void viewcitizensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcitizensActionPerformed
        Viewcitizens vc = null;
        try {
            vc = new Viewcitizens(id,conn);
        } catch (SQLException ex) {
            Logger.getLogger(Police.class.getName()).log(Level.SEVERE, null, ex);
        }
        vc.setVisible(true);
    }//GEN-LAST:event_viewcitizensActionPerformed

    private void viewleadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewleadsActionPerformed
        PLeads pl = new PLeads(id,conn);
        pl.setVisible(true);        
    }//GEN-LAST:event_viewleadsActionPerformed

    private void viewcrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcrimeActionPerformed
        viewcrime vc = new viewcrime(id,conn);
        vc.setVisible(true);
    }//GEN-LAST:event_viewcrimeActionPerformed

    private void addcrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcrimeActionPerformed
        AddCrime ac = new AddCrime(id,conn);
        ac.setVisible(true);
    }//GEN-LAST:event_addcrimeActionPerformed

    private void addvictimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvictimsActionPerformed
        Viewvictims vv = null;
        try {
            vv = new Viewvictims(id,conn);
        } catch (SQLException ex) {
            Logger.getLogger(Police.class.getName()).log(Level.SEVERE, null, ex);
        }
        vv.setVisible(true);
    }//GEN-LAST:event_addvictimsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Police.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Police().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcrime;
    private javax.swing.JButton addcriminalrecord;
    private javax.swing.JButton addcriminals;
    private javax.swing.JButton addvictims;
    private javax.swing.JScrollPane criminaltablepane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewcitizens;
    private javax.swing.JButton viewcrime;
    private javax.swing.JPanel viewcriminalpanel;
    private javax.swing.JButton viewcriminalrecord;
    private javax.swing.JTable viewcriminaltable;
    private javax.swing.JButton viewleads;
    // End of variables declaration//GEN-END:variables
}
